name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - streamlit
  - python-dotenv
  - openpyxl
  - pytest
  - numpy
  - scikit-learn
  - requests
  - boto3
  - altair
  - pip
  - pip:
      - -r infra/requirements/requirements.txt
      - fastapi
      - prometheus_client
      - structlog
      - httpx
